import {state} from './store.js';
import {escape as e,plain,external,day} from './utils.js';
import {icon,svg} from './icons.js';
import {content} from './window.js';
const routeButton=(route,label,cls='row')=>`<button class="${cls}" data-route="${e(JSON.stringify(route))}">${label}</button>`;
export {routeButton};
export function note(){content('메모',`<div class="page"><p class="eyebrow">방문자에게</p><h1>작업실에 남긴 메모</h1><p class="note-reading">${e(state.workspace.note)}</p></div>`);}
export function shared(){
 const items=state.workspace.resources.filter(r=>r.area==='training');
 content('공유 자료',`<div class="page"><p class="eyebrow">FILES & LINKS</p><h1>함께 쓰는 자료</h1><p class="muted">공유 중인 파일과 자료실입니다.</p>${items.map(r=>external(r.url,`${r.name} · ${r.category}`,'channel')).join('')||'<p>아직 공유 중인 자료가 없습니다.</p>'}${state.editor?routeButton({view:'admin',tab:'resources',area:'training'},'공유 자료 추가','secondary'):''}</div>`);
}
const empty=(title,body)=>`<div class="empty">${svg('folder')}<h2>${e(title)}</h2><p>${e(body)}</p></div>`;
export function programs(){
 content('만든 도구',`<div class="page"><p class="eyebrow">MADE IN MY CLASSROOM</p><h1>교실에서 시작한 도구들</h1><p class="muted">불편했던 순간을, 조금 더 편리하게.</p><div class="program-extras"><button class="secondary" data-route='{"view":"workflows"}'>프로젝트</button><button class="secondary" data-route='{"view":"physics"}'>놀이터</button></div><div class="program-grid">${state.site.programs.map(p=>routeButton({view:'program',id:p.id},`${icon('sheet',p.icon)}<span class="badge">${p.status==='live'?'사용 가능':p.status==='planned'?'기획 중':'개발 중'}</span><h2>${e(p.label)}</h2><p>${e(p.desc==='무엇을 하는 도구인지 한 줄'?'프로그램 소개를 준비하고 있습니다.':p.desc)}</p>`,'program-card')).join('')}</div></div>`);
}
export function program(id){const p=state.site.programs.find(x=>x.id===id);if(!p)return programs();content(p.label,`<div class="page program-detail">${icon('sheet',p.icon)}<p class="eyebrow">${e(p.version)} · ${p.status==='live'?'사용 가능':'개발 중'}</p><h1>${e(p.label)}</h1><p class="lead">${e(p.desc==='무엇을 하는 도구인지 한 줄'?'소개를 준비하고 있습니다.':p.desc)}</p>${p.why&&!p.why.includes('한 줄로 적기')?`<h2>만들게 된 이유</h2><p>${e(p.why)}</p>`:''}<div class="launch-choices">${routeButton({view:'browser',id:p.id,mode:'detail'},`${svg('note')}<span><strong>설명 보기</strong><small>사용 방법과 배포 안내</small></span>`,'launch-choice')}${p.url?routeButton({view:'browser',id:p.id,mode:'launch'},`${svg('play')}<span><strong>바로 실행</strong><small>작업실 안에서 웹앱 열기</small></span>`,'launch-choice launch-primary'):''}</div>${external(p.github,'소스 코드','text')}<p class="muted">상세 페이지에서 사용 방법과 배포 파일을 확인할 수 있습니다.</p></div>`);}
export function records(date='',id=''){
 const all=[...state.workspace.records].sort((a,b)=>b.date.localeCompare(a.date));const shown=date?all.filter(r=>r.date===date):all;const selected=shown.find(r=>r.id===id)||shown[0];
 content('캘린더 · 기록',`<div class="record-layout"><aside class="record-list"><div class="list-heading"><strong>${date?e(date):'전체 기록'}</strong>${date?routeButton({view:'records'},'전체','text'):''}</div>${shown.map(r=>routeButton({view:'records',date,id:r.id},`<small>${e(r.date)} · ${e(r.kind)}</small><strong>${e(r.title)}</strong>`,`row ${selected?.id===r.id?'selected':''}`)).join('')||'<p class="muted">등록된 기록이 없습니다.</p>'}</aside><article class="reading">${selected?`<p class="eyebrow">${e(selected.date)} · ${e(selected.kind)}</p><h1>${e(selected.title)}</h1><div class="prose">${e(selected.body)}</div>`:empty('아직 기록이 없는 날입니다','다른 날짜를 선택하거나 전체 기록을 열어보세요.')}${state.editor?routeButton({view:'admin',tab:'records',id:selected?.id||'',date:date||day()},selected?'이 기록 수정':'기록 추가','secondary'):''}</article></div>`);
}
export function finder(area='recommend',category='',folder='',id=''){
 const items=state.workspace.resources.filter(r=>r.area===area),categories=[...new Set(items.map(r=>r.category))];category=categories.includes(category)?category:categories[0];
 const folders=[...new Set(items.filter(r=>r.category===category).map(r=>r.folder))];folder=folders.includes(folder)?folder:folders[0];const shown=items.filter(r=>r.category===category&&r.folder===folder);const item=shown.find(r=>r.id===id)||shown[0];
 const view=area==='training'?'training':'recommend';
 content(area==='training'?'연수 자료':'추천 도구함',`<div class="finder"><aside class="finder-sidebar"><p class="eyebrow">분야별 모아보기</p>${categories.map(c=>routeButton({view,category:c},`${svg('folder')} ${e(c)}`,`row ${category===c?'selected':''}`)).join('')}${state.editor?routeButton({view:'admin',tab:'resources',area},`${svg('plus')} 자료 추가`,'row'):''}</aside><section class="finder-items"><p class="eyebrow">${e(category||'자료실')}</p>${folders.map(f=>`<div class="folder-group">${routeButton({view,category,folder:f},`${svg('folder')} ${e(f)}`,`row folder-row ${f===folder?'current':''}`)}${f===folder?shown.map(r=>routeButton({view,category,folder,id:r.id},`${svg(r.kind==='sheet'?'sheet':r.kind==='folder'?'folder':'link')}<span>${e(r.name)}<small>${r.kind==='skill'?'스킬':e(r.by||'공유 자료')}</small></span>`,`row file-row ${r.id===item?.id?'selected':''}`)).join(''):''}</div>`).join('')}</section><article class="finder-preview">${item?`${icon(item.kind,e(item.image||''))}<p class="eyebrow">${e(category)} / ${e(folder)}</p><h1>${e(item.name)}</h1><p class="prose">${e(item.body)}</p>${item.by?`<p class="muted">${e(item.by)}</p>`:''}${external(item.url,item.kind==='skill'?'설치 안내 열기':'자료 열기')}${state.editor?routeButton({view:'admin',tab:'resources',id:item.id},'자료 수정','text'):''}`:empty('자료를 모아둘 공간','관리 화면에서 분야와 폴더를 정하고 자료 링크를 추가할 수 있습니다.')}</article></div>`);
}
export function workflows(){content('프로젝트 · 작업 흐름',`<div class="page"><p class="eyebrow">CONNECT THE TOOLS</p><h1>도구를 함께 쓰는 방법</h1>${state.site.workflows.map(w=>`<section class="workflow"><h2>${e(plain(w.name))}</h2><p>${e(plain(w.desc))}</p><div class="workflow-steps">${(w.steps||[]).map((s,i)=>{const p=state.site.programs.find(p=>p.id===s.programId);return routeButton({view:'program',id:p?.id},`<span class="step-number">0${i+1}</span>${icon('sheet',p?.icon)}<strong>${e(p?.label||'도구')}</strong><small>${e(plain(s.role))}</small>`,'step');}).join('')}</div>${w.problem?`<p>${e(plain(w.problem))}</p>`:''}${w.outcome?`<p class="callout">${e(plain(w.outcome))}</p>`:''}</section>`).join('')}</div>`);}
export function about(){const f=state.site.fields;content('소개 · 채널',`<div class="page about"><p class="eyebrow">${e(plain(f.role))}</p><h1>게으른 교사의 작업실</h1><p class="manifesto">교사가 한가해야,<br>교육이 성장한다.</p><p>수업과 행정의 번거로움을 줄이는 도구를 만들고,<br>만들면서 배운 것들을 나눕니다.</p>${f['now.text']?`<div class="callout"><strong>요즘 하고 있는 일</strong><p>${e(plain(f['now.text']))}</p></div>`:''}<h2>다른 곳에서도 만나요</h2><div class="channel-grid">${state.site.channels.map(c=>external(c.url,`${c.name} · ${c.desc}`,'channel')).join('')}</div><h2>연락하기</h2><a href="mailto:${e(plain(f['contact.email']))}">${e(plain(f['contact.email']))}</a><p>카카오톡 · ${e(plain(f['contact.kakao']))}</p><a class="text" href="classic.html">기존 목록형 홈페이지 보기 ↗</a></div>`);}
export function search(query=''){
 const q=query.trim().toLocaleLowerCase();const entries=[...state.site.programs.map(p=>({name:p.label,body:p.desc,type:'프로그램',route:{view:'program',id:p.id}})),...state.workspace.records.map(r=>({name:r.title,body:r.body,type:r.date,route:{view:'records',id:r.id}})),...state.workspace.resources.map(r=>({name:r.name,body:r.body,type:r.category,route:{view:r.area==='training'?'training':'recommend',category:r.category,folder:r.folder,id:r.id}})),...state.workspace.shortcuts.map(s=>({name:s.name,body:s.url,type:'바로가기',url:s.url}))];
 const results=q?entries.filter(r=>`${r.name} ${r.body} ${r.type}`.toLowerCase().includes(q)):[];
 content('작업실 검색',`<div class="page"><form id="search-form" class="search-form"><label for="search-query">프로그램, 기록, 자료 찾기</label><div><input id="search-query" name="query" type="search" value="${e(query)}" placeholder="예: 시험, AI, 연수"><button class="primary">검색</button></div></form><p class="muted">${q?`${results.length}개의 결과`:'찾고 싶은 이름이나 내용을 입력하세요.'}</p><div>${results.map(r=>r.route?routeButton(r.route,`<small>${e(r.type)}</small><strong>${e(r.name)}</strong><span>${e(r.body.slice(0,120))}</span>`,'search-result'):external(r.url,r.name,'search-result')).join('')}</div></div>`);
}
