import {state,isAdmin,update} from './store.js';
import {escape as e,plain,external,day} from './utils.js';
import {icon,svg} from './icons.js';
import {content} from './window.js';
import {resolvedWorkflows} from './workflow-data.js';
import {about as aboutView} from './about.js';
const routeButton=(route,label,cls='row')=>`<button class="${cls}${route.view==='admin'||route.view==='editNote'?' admin-only':''}" data-route="${e(JSON.stringify(route))}">${label}</button>`;
export {routeButton};
export function note(id=''){const memo=(state.workspace.memos||[]).find(item=>item.id===id)||(state.workspace.memos||[])[0];if(!memo)return;const editable=state.editor&&isAdmin();content(memo.name,`<div class="page"><h1>${e(memo.name)}</h1><p class="note-reading">${e(memo.text)}</p>${memo.checklist.length?`<ul class="note-checklist">${memo.checklist.map((item,index)=>`<li class="${item.done?'done':''}">${editable?`<label><input type="checkbox" data-note-check="${e(memo.id)}:${index}" ${item.done?'checked':''}>${e(item.text)}</label>`:`${item.done?'✓ ':''}${e(item.text)}`}</li>`).join('')}</ul>`:''}${state.editor?routeButton({view:'editNote',id:memo.id},'메모 편집','secondary'):''}</div>`);document.querySelectorAll('[data-note-check]').forEach(control=>control.addEventListener('change',()=>{const [memoId,index]=control.dataset.noteCheck.split(':'),next=structuredClone(state.workspace),item=next.memos.find(entry=>entry.id===memoId)?.checklist[Number(index)];if(!item)return;item.done=control.checked;update(next);}));}
export function usage(){content('작업실 사용법',`<div class="page compact-page"><p class="eyebrow">HELP</p><h1>작업실 사용법</h1><p>Dock에서 프로그램을 열고, 바탕화면 폴더에서 자료와 기록을 살펴보세요.</p><p>창의 왼쪽 위 버튼으로 닫거나 최소화할 수 있고, 검색은 ⌘K 또는 Ctrl+K로 열 수 있습니다.</p></div>`);}
export function shared(){
 const items=state.workspace.resources.filter(r=>r.area==='training');
 content('공유 자료',`<div class="page"><p class="eyebrow">FILES & LINKS</p><h1>함께 쓰는 자료</h1><p class="muted">공유 중인 파일과 자료실입니다.</p>${items.map(r=>external(r.url,`${r.name} · ${r.category}`,'channel')).join('')||'<p>아직 공유 중인 자료가 없습니다.</p>'}</div>`);
}
const empty=(title,body)=>`<div class="empty">${svg('folder')}<h2>${e(title)}</h2><p>${e(body)}</p></div>`;
export function programs(){
 content('만든 프로그램',`<div class="page programs-folder"><div class="folder-caption">${icon('folder')}<div><h1>만든 프로그램</h1><p class="muted">${state.site.programs.length}개의 프로그램</p></div></div><div class="app-folder-grid">${state.site.programs.map(p=>routeButton({view:'program',id:p.id},`${icon('sheet',p.icon)}<strong>${e(p.label)}</strong>`,'folder-app')).join('')}</div><div class="program-extras"><button class="secondary" data-route='{"view":"workflows"}'>프로젝트</button><button class="secondary" data-route='{"view":"physics"}'>놀이터</button></div></div>`);
}
export function program(id){const p=state.site.programs.find(x=>x.id===id);if(!p)return programs();const summary=p.desc==='무엇을 하는 도구인지 한 줄'?'소개를 준비하고 있습니다.':p.desc;const introduction=p.why&&!p.why.includes('한 줄로 적기')?`<section><h2>소개</h2><p>${e(p.why)}</p></section>`:'';const update=p.version?`<section><h2>업데이트</h2><p class="muted">현재 표시된 버전: ${e(p.version)}</p></section>`:'';content(p.label,`<div class="page program-detail">${icon('sheet',p.icon)}<p class="eyebrow">${p.status==='live'?'사용 가능':'개발 중'}</p><h1>${e(p.label)}</h1><p class="lead">${e(summary)}</p>${introduction}<section><h2>사용 및 실행</h2><p class="muted">프로그램 설명은 작업실 안의 브라우저에서 열 수 있습니다.</p><div class="launch-choices">${routeButton({view:'browser',id:p.id,mode:'detail'},`${svg('note')}<span><strong>설명 보기</strong><small>소개와 사용 안내 열기</small></span>`,'launch-choice')}${p.url?routeButton({view:'browser',id:p.id,mode:'launch'},`${svg('play')}<span><strong>바로 실행</strong><small>작업실 안에서 웹앱 열기</small></span>`,'launch-choice launch-primary'):''}</div></section>${update}${external(p.github,'소스 코드','text')}</div>`);}
export function records(date='',id=''){
 const all=[...state.workspace.records].sort((a,b)=>b.date.localeCompare(a.date));const shown=date?all.filter(r=>r.date===date):all;const selected=shown.find(r=>r.id===id)||shown[0];
 content('캘린더 · 기록',`<div class="record-layout"><aside class="record-list"><div class="list-heading"><strong>${date?e(date):'전체 기록'}</strong>${date?routeButton({view:'records'},'전체','text'):''}</div>${shown.map(r=>routeButton({view:'records',date,id:r.id},`<small>${e(r.date)} · ${e(r.kind)}</small><strong>${e(r.title)}</strong>`,`row ${selected?.id===r.id?'selected':''}`)).join('')||'<p class="muted">등록된 기록이 없습니다.</p>'}</aside><article class="reading">${selected?`<p class="eyebrow">${e(selected.date)} · ${e(selected.kind)}</p><h1>${e(selected.title)}</h1><div class="prose">${e(selected.body)}</div>`:empty('아직 기록이 없는 날입니다','다른 날짜를 선택하거나 전체 기록을 열어보세요.')}${state.editor?routeButton({view:'admin',tab:'records',id:selected?.id||'',date:date||day()},selected?'이 기록 수정':'기록 추가','secondary'):''}</article></div>`);
}
export function finder(area='recommend',category='',folder='',id=''){
 const archive=area==='archive',items=archive?state.workspace.archives:state.workspace.resources.filter(r=>r.area===area),categories=[...new Set(items.map(r=>r.category))];category=categories.includes(category)?category:categories[0];
 const folders=[...new Set(items.filter(r=>r.category===category).map(r=>r.folder))];folder=folders.includes(folder)?folder:'';const shown=folder?items.filter(r=>r.category===category&&r.folder===folder):[];const item=shown.find(r=>r.id===id);
 const view=archive?'archives':area==='training'?'training':'recommend',title=archive?'자료 아카이브':area==='training'?'연수 자료':'추천 도구함',tab=archive?'archives':'resources';
 content(title,`<div class="finder ${item?'has-preview':''}"><aside class="finder-sidebar"><p class="eyebrow">분야별 모아보기</p>${categories.map(c=>routeButton({view,category:c},`${svg('folder')} ${e(c)}`,`row ${category===c?'selected':''}`)).join('')}${state.editor?routeButton({view:'admin',tab,area,category,folder},`${svg('plus')} 자료 추가`,'row'):''}</aside><section class="finder-folders"><p class="eyebrow">${e(category||'자료실')}</p>${folders.map(f=>routeButton({view,category,folder:f},`${svg('folder')} ${e(f)}`,`row folder-row ${f===folder?'selected':''}`)).join('')}</section><section class="finder-items"><p class="eyebrow">${folder?e(folder):'폴더 선택'}</p>${shown.map(r=>routeButton({view,category,folder,id:r.id},`${icon(r.kind,e(r.image||''))}<span>${e(r.name)}<small>${r.kind==='skill'?'스킬':e(r.by||'공유 자료')}${r.kind==='folder'?' · 외부 폴더 ↗':''}</small></span>`,`row file-row ${r.id===item?.id?'selected':''}`)).join('')||(folder?'<p class="empty-copy">이 폴더에는 아직 항목이 없습니다.</p>':'<p class="empty-copy">폴더를 선택하세요.</p>')}</section>${item?`<article class="finder-preview"><header class="resource-heading">${icon(item.kind,e(item.image||''))}<div><p class="eyebrow">${e(category)} / ${e(folder)}</p><h1>${e(item.name)}</h1></div></header><p class="prose">${e(item.body)}</p>${item.by?`<p class="muted">${e(item.by)}</p>`:''}${external(item.url,item.kind==='skill'?'설치 안내 열기':item.kind==='folder'?'외부 폴더 열기':'자료 열기')}${state.editor?routeButton({view:'admin',tab,id:item.id,area,category,folder},'자료 수정','text'):''}</article>`:''}</div>`);
}
export function workflows(category='',folder='',id=''){
 const workflows=resolvedWorkflows(state.site.workflows||[],state.workspace.workflowOverrides),custom=state.workspace.projects||[], categories=[...new Set([...workflows.map(w=>plain(w.tag)||'프로젝트'),...custom.map(item=>item.category)])];
 const grouped=category?workflows.filter(w=>(plain(w.tag)||'프로젝트')===category):[],customGroup=category?custom.filter(item=>item.category===category):[];
 const folders=[...new Set([...grouped.map(w=>plain(w.name)),...customGroup.map(item=>item.folder)])],selected=grouped.find(w=>plain(w.name)===folder),customItems=customGroup.filter(item=>item.folder===folder);
 const items=selected?[{id:'overview',name:'프로젝트 개요',body:plain(selected.desc),kind:'folder'},...(selected.steps||[]).map((step,index)=>{const p=state.site.programs.find(program=>String(program.id)===String(step.programId));return{id:`step-${index}`,name:p?.label||'도구',body:plain(step.role),kind:'sheet',image:p?.icon||'',programId:p?.id};}),...(selected.outcome?[{id:'outcome',name:'현재 메모',body:plain(selected.outcome),kind:'note'}]:[])]:customItems.map(item=>({...item,kind:item.kind||'folder'}));
 const item=items.find(entry=>entry.id===id);
 content('프로젝트 · 작업 흐름',`<div class="finder workflow-finder ${item?'has-preview':''}"><aside class="finder-sidebar"><p class="eyebrow">분야</p>${categories.map(name=>routeButton({view:'workflows',category:name},`${svg('folder')} ${e(name)}`,`row ${name===category?'selected':''}`)).join('')}${state.editor?routeButton({view:'admin',tab:'projects'},`${svg('plus')} 프로젝트 추가`,'row'):''}</aside><section class="finder-folders"><p class="eyebrow">${e(category||'프로젝트')}</p>${folders.map(name=>routeButton({view:'workflows',category,folder:name},`${svg('folder')} ${e(name)}`,`row folder-row ${name===folder?'selected':''}`)).join('')||'<p class="empty-copy">분야를 선택하세요.</p>'}</section><section class="finder-items"><p class="eyebrow">${e(folder||'폴더 선택')}</p>${items.map(entry=>routeButton({view:'workflows',category,folder,id:entry.id},`${icon(entry.kind,e(entry.image||''))}<span>${e(entry.name)}<small>${e(entry.body)}</small></span>`,`row file-row ${entry.id===item?.id?'selected':''}`)).join('')||'<p class="empty-copy">왼쪽에서 프로젝트를 선택하세요.</p>'}</section>${item?`<article class="finder-preview">${icon(item.kind,e(item.image||''))}<p class="eyebrow">${e(category)} / ${e(folder)}</p><h1>${e(item.name)}</h1><p class="prose">${e(item.body)}</p>${item.programId?routeButton({view:'program',id:item.programId},'프로그램 보기','secondary'):''}${item.url?external(item.url,'연결 열기','text'):''}${item.id==='overview'&&selected?.problem?`<p class="muted">${e(plain(selected.problem))}</p>`:''}${state.editor&&selected?routeButton({view:'admin',tab:'workflows',id:selected.id,category,folder},'프로젝트 편집','text'):state.editor&&customItems.some(entry=>entry.id===item.id)?routeButton({view:'admin',tab:'projects',id:item.id},'프로젝트 수정','text'):''}</article>`:''}</div>`);
}
export function about(){aboutView();}
export function search(query=''){
 const q=query.trim().toLocaleLowerCase();const entries=[...state.site.programs.map(p=>({name:p.label,body:p.desc,type:'프로그램',route:{view:'program',id:p.id}})),...state.workspace.records.map(r=>({name:r.title,body:r.body,type:r.date,route:{view:'records',id:r.id}})),...state.workspace.resources.map(r=>({name:r.name,body:r.body,type:r.category,route:{view:r.area==='training'?'training':'recommend',category:r.category,folder:r.folder,id:r.id}})),...state.workspace.shortcuts.map(s=>({name:s.name,body:s.url,type:'바로가기',url:s.url}))];
 const results=q?entries.filter(r=>`${r.name} ${r.body} ${r.type}`.toLowerCase().includes(q)):[];
 content('작업실 검색',`<div class="page"><form id="search-form" class="search-form"><label for="search-query">프로그램, 기록, 자료 찾기</label><div><input id="search-query" name="query" type="search" value="${e(query)}" placeholder="예: 시험, AI, 연수"><button class="primary">검색</button></div></form><p class="muted">${q?`${results.length}개의 결과`:'찾고 싶은 이름이나 내용을 입력하세요.'}</p><div>${results.map(r=>r.route?routeButton(r.route,`<small>${e(r.type)}</small><strong>${e(r.name)}</strong><span>${e(r.body.slice(0,120))}</span>`,'search-result'):external(r.url,r.name,'search-result')).join('')}</div></div>`);
}
