const {test, expect} = require('@playwright/test');
const seed = require('../../src/studio/seed.json');

const encode = value => value == null ? {nullValue: null} : typeof value === 'string' ? {stringValue: value} : typeof value === 'number' ? {integerValue: String(value)} : typeof value === 'boolean' ? {booleanValue: value} : Array.isArray(value) ? {arrayValue: {values: value.map(encode)}} : {mapValue: {fields: Object.fromEntries(Object.entries(value).map(([key, item]) => [key, encode(item)]))}};

async function prepare(page) {
  await page.route('https://firestore.googleapis.com/**', async route => {
    if (route.request().url().includes(':batchGet')) return route.fulfill({json: [{found: {name: 'projects/p/databases/(default)/documents/personal-site/main', ...encode(seed).mapValue}}, {missing: 'projects/p/databases/(default)/documents/personal-site/desktop-v1'}]});
    return route.fulfill({status: 404, json: {}});
  });
  await page.route('https://www.gstatic.com/firebasejs/**', route => route.fulfill({contentType: 'application/javascript', body: route.request().url().includes('firebase-app') ? 'export const initializeApp=()=>({});' : "const user={email:'seungyeon980808@gmail.com',emailVerified:true,getIdToken:async()=> 'test-token'};export const getAuth=()=>({currentUser:null,authStateReady:async()=>{}});export const onAuthStateChanged=(a,cb)=>cb(null);export class GoogleAuthProvider{};export const signInWithPopup=async()=>({user});export const signOut=async()=>{};"}));
  await page.emulateMedia({reducedMotion: 'reduce'});
  await page.goto('/');
  await page.getByRole('button', {name: /(노트북 열고|휴대폰 들고) 작업실 들어가기/, exact: true}).click();
  await expect(page.locator('#entrance')).toBeHidden();
}

test('visitor sees the approved profile and centered contact without owner controls', async ({page}) => {
  await prepare(page);
  await page.getByRole('button', {name: '인사드립니다', exact: true}).click();
  await expect(page.getByRole('heading', {name: '인사드립니다', exact: true})).toBeVisible();
  await expect(page.locator('.about-hammer')).toHaveAttribute('src', 'assets/about/hammer.webp');
  await expect(page.locator('.about-intro-copy')).toContainText('AI가 저에게 망치를 쥐어 주었습니다.');
  await expect(page.getByRole('heading', {name: '교사가 한가해야, 교육이 성장한다', exact: true})).toBeVisible();
  await expect(page.getByRole('heading', {name: '걸어온 길', exact: true})).toBeVisible();
  await expect(page.getByRole('heading', {name: '바이브 코딩', exact: true})).toBeVisible();
  await expect(page.locator('.about-page .admin-only')).toHaveCount(0);
  await page.screenshot({path: '.omo/evidence/owner-refinement/about/visitor-1280.png'});
  await page.locator('#window-body').evaluate(element => { element.scrollTop = element.scrollHeight * .48; });
  await page.screenshot({path: '.omo/evidence/owner-refinement/about/visitor-middle-1280.png'});
  await page.locator('#window-body').evaluate(element => { element.scrollTop = element.scrollHeight; });
  await page.screenshot({path: '.omo/evidence/owner-refinement/about/visitor-bottom-1280.png'});
  await page.locator('#window-body').getByRole('button', {name: '연락하기', exact: true}).click();
  await expect(page.getByRole('heading', {name: '연락하기', exact: true})).toBeVisible();
  await expect(page.getByRole('link', {name: '전화하기', exact: true})).toHaveAttribute('href', 'tel:01049174332');
  await page.setViewportSize({width: 375, height: 812});
  expect(await page.locator('#window-body').evaluate(element => element.scrollWidth <= element.clientWidth + 1)).toBe(true);
  await page.screenshot({path: '.omo/evidence/owner-refinement/about/contact-375.png'});
});

test('owner drafts, previews, restores, and edits profile goals and same-month records', async ({page}) => {
  await prepare(page);
  await page.getByRole('button', {name: '작업실 설정', exact: true}).click();
  await page.getByRole('button', {name: 'Google 관리자 로그인', exact: true}).click();
  await page.getByRole('button', {name: '초안 편집 시작', exact: true}).click();
  await page.getByRole('button', {name: '창 닫기', exact: true}).click();
  await page.getByRole('button', {name: '인사드립니다', exact: true}).click();
  await page.screenshot({path: '.omo/evidence/owner-refinement/about/owner-top-1280.png'});
  await page.locator('#window-body').evaluate(element => { element.scrollTop = element.scrollHeight * .48; });
  await page.screenshot({path: '.omo/evidence/owner-refinement/about/owner-middle-1280.png'});
  await page.getByText('소개 · 철학 편집', {exact: true}).click();
  await page.locator('form[data-profile-copy] textarea[name="intro"]').fill('초안으로 쓴 새로운 인사입니다.');
  await page.locator('form[data-profile-copy]').getByRole('button', {name: '저장', exact: true}).click();
  await expect(page.locator('.about-intro-copy')).toHaveText('초안으로 쓴 새로운 인사입니다.');
  await page.getByText('목표 추가', {exact: true}).first().click();
  await page.locator('form[data-profile-add-goal="short"] input[name="value"]').fill('짧은 목표');
  await page.locator('form[data-profile-add-goal="short"]').getByRole('button', {name: '추가', exact: true}).click();
  await expect(page.locator('.about-goals').first()).toContainText('짧은 목표');
  let goal = page.locator('.about-goals').first().locator('li').filter({hasText: '짧은 목표'});
  await goal.getByText('수정', {exact: true}).click();
  await goal.locator('textarea[name="value"]').fill('고친 짧은 목표');
  await goal.getByRole('button', {name: '저장', exact: true}).click();
  await expect(page.locator('.about-goals').first()).toContainText('고친 짧은 목표');
  await page.getByText('경력 추가', {exact: true}).click();
  await page.locator('form[data-profile-add-career] input[name="year"]').fill('2027');
  await page.locator('form[data-profile-add-career] input[name="title"]').fill('새 경력');
  await page.locator('form[data-profile-add-career]').getByRole('button', {name: '추가', exact: true}).click();
  await expect(page.locator('.about-career')).toContainText('새 경력');
  await page.getByText('기록 추가', {exact: true}).click();
  await page.locator('form[data-profile-add-vibe] input[name="month"]').fill('2026-01');
  await page.locator('form[data-profile-add-vibe] input[name="title"]').fill('새 기록');
  await page.locator('form[data-profile-add-vibe] textarea[name="reflection"]').fill('기록 소감');
  await page.locator('form[data-profile-add-vibe]').getByRole('button', {name: '추가', exact: true}).click();
  await expect(page.locator('.about-vibe-month').first()).toContainText('새 기록');
  let vibe = page.locator('.about-vibe-month').first().locator('li').filter({hasText: '새 기록'});
  await vibe.getByText('수정', {exact: true}).click();
  await vibe.locator('input[name="title"]').fill('고친 기록');
  await vibe.getByRole('button', {name: '저장', exact: true}).click();
  await page.getByText('기록 추가', {exact: true}).click();
  await page.locator('form[data-profile-add-vibe] input[name="month"]').fill('2026-01');
  await page.locator('form[data-profile-add-vibe] input[name="title"]').fill('같은 달 두번째 기록');
  await page.locator('form[data-profile-add-vibe]').getByRole('button', {name: '추가', exact: true}).click();
  await expect(page.locator('.about-vibe-month').first()).toContainText('고친 기록');
  await expect(page.locator('.about-vibe-month').first()).toContainText('같은 달 두번째 기록');
  const draft = await page.evaluate(() => JSON.parse(localStorage.getItem('studio-draft-v1')).workspace.profile);
  expect(draft.intro).toBe('초안으로 쓴 새로운 인사입니다.');
  expect(draft.shortGoals).toContain('고친 짧은 목표');
  expect(draft.career.some(entry => entry.title === '새 경력')).toBe(true);
  expect(draft.vibes.filter(entry => entry.month === '2026-01')).toHaveLength(2);
  await page.screenshot({path: '.omo/evidence/owner-refinement/about/owner-draft-1280.png', fullPage: true});
  await page.getByRole('button', {name: '창 닫기', exact: true}).click();
  await page.getByRole('button', {name: '공개 화면 보기', exact: true}).click();
  await page.getByRole('button', {name: '인사드립니다', exact: true}).click();
  await expect(page.locator('.about-intro-copy')).not.toHaveText('초안으로 쓴 새로운 인사입니다.');
  await expect(page.locator('.about-page .admin-only')).toHaveCount(0);
  await page.getByRole('button', {name: '창 닫기', exact: true}).click();
  await page.getByRole('button', {name: '작업실 설정', exact: true}).click();
  await page.getByRole('button', {name: '초안 편집 시작', exact: true}).click();
  await page.getByRole('button', {name: '창 닫기', exact: true}).click();
  await page.getByRole('button', {name: '인사드립니다', exact: true}).click();
  await expect(page.locator('.about-intro-copy')).toHaveText('초안으로 쓴 새로운 인사입니다.');
  await page.reload();
  await expect(page.locator('#entrance')).toBeHidden();
  await page.getByRole('button', {name: '작업실 설정', exact: true}).click();
  await page.getByRole('button', {name: 'Google 관리자 로그인', exact: true}).click();
  await page.getByRole('button', {name: '초안 편집 시작', exact: true}).click();
  await page.getByRole('button', {name: '창 닫기', exact: true}).click();
  await page.getByRole('button', {name: '인사드립니다', exact: true}).click();
  await expect(page.locator('.about-vibe-month').first()).toContainText('고친 기록');
  await expect(page.locator('.about-vibe-month').first()).toContainText('같은 달 두번째 기록');
  vibe = page.locator('.about-vibe-month').first().locator('li').filter({hasText: '고친 기록'});
  await vibe.getByText('삭제', {exact: true}).click();
  await expect(page.locator('.about-vibes')).not.toContainText('고친 기록');
  goal = page.locator('.about-goals').first().locator('li').filter({hasText: '고친 짧은 목표'});
  await goal.getByText('삭제', {exact: true}).click();
  await expect(page.locator('.about-goals').first()).not.toContainText('고친 짧은 목표');
});
