const $=s=>document.querySelector(s);
const apps=[['ExamPool','logo-exampool','exam-pool','근거를 모으고 문항과 시험 세트를 구성하는 출제 도구'],['5E','logo-5e','physics-draw','시험문제에 필요한 과학 그림을 직접 만드는 편집기'],['HwpPalette','logo-hwp','hwp-palette','자주 사용하는 한글 편집 작업을 모아 둔 도구'],['EveryKey','logo-everykey','everykey','반복되는 컴퓨터 작업을 줄이는 도구']];
const records={'2026-08-30':{title:'해커톤을 마치고',text:'어제 서울시교육청 2호 개발자 해커톤(도전형) 연수가 끝났다. 여러모로 배운점이 많았던 연수였다. 맥을 처음으로 메인으로 두고 작업을 했으며, 협업이라는 것을 제대로 처음 해봤다. 확실히 혼자할때랑은 느낌 자체가 달랐다. 소통의 중요성을 깨달았다고 해야하나?',kind:'개발일지'},'2026-07-23':{title:'도구를 연결하며 배운 것',text:'MCP라는게 어떤건지 느낌으로만 알고 있었는데, 실제로 내가 만든 웹앱에 달아서 사용해보니까 뭔지 알겠다. Exam Pool 2일차인데 벌써 퀄리티가 꽤 괜찮다.',kind:'개발일지'},'2026-07-24':{title:'방학에 할 일',text:'해커톤 연수 준비\n학교업무관리시스템 구축\n시험문제출제 워크플로우 구축\n2학기 수업 준비\n프로그래밍 학습',kind:'생각'}};
let month=new Date(2026,7,1),editing=false,lastFocus=null;
const load=(key,fallback)=>{try{return JSON.parse(localStorage.getItem(key))??fallback}catch{return fallback}};
let shortcuts=load('studio-links',[]),note=load('studio-note','작업실에 오신 것을 환영합니다.\n프로그램은 아래 Dock에서, 기록은 캘린더에서 확인하실 수 있습니다.');
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function store(key,value){try{localStorage.setItem(key,JSON.stringify(value));$('#saveState').textContent='이 브라우저에 저장되었습니다';return true}catch{$('#saveState').textContent='저장 공간을 사용할 수 없습니다';return false}}
function calendar(){const y=month.getFullYear(),m=month.getMonth();$('#month').textContent=`${y}년 ${m+1}월`;$('#dates').innerHTML='<span></span>'.repeat(new Date(y,m,1).getDay());for(let d=1;d<=new Date(y,m+1,0).getDate();d++){const key=`${y}-${String(m+1).padStart(2,'0')}-${String(d).padStart(2,'0')}`;const b=document.createElement('button');b.textContent=d;b.className=records[key]?'has':'';b.setAttribute('aria-label',`${m+1}월 ${d}일${records[key]?' 기록 있음':''}`);b.onclick=()=>journal(key);$('#dates').append(b)}}
function openWindow(title,html){lastFocus=document.activeElement;$('#windowTitle').textContent=title;$('#windowBody').innerHTML=html;$('#window').style.transform='';if(!$('#window').open)$('#window').showModal();$('#close').focus()}
function closeWindow(){$('#window').close();lastFocus?.focus()}
$('#close').onclick=closeWindow;$('#expand').onclick=()=>$('#window').classList.toggle('full');
function journal(key){const r=records[key];openWindow('기록',`<div class="finder"><section>${Object.entries(records).map(([k,v])=>`<button class="row ${k===key?'active':''}" data-date="${k}">${k}<small>${esc(v.title)}</small></button>`).join('')}</section><section class="detail" style="grid-column:span 2">${r?`<p class="muted">${key} · ${r.kind} · 공개 기록 발췌</p><h1>${r.title}</h1><p style="white-space:pre-line;line-height:2">${r.text}</p><button class="text" data-open="programs">관련 도구 살펴보기 ↗</button>`:`<h2>${key}</h2><p>이 날짜에는 공개된 기록이 없습니다.</p><button class="text" data-date="2026-08-30">최근 기록 보기 ↗</button>`}</section></div>`)}
const categories={'AI·개발':[['에이전트 스킬','스킬을 분야별로 저장하는 공간','추천 스킬을 등록하면 설명과 설치 안내를 이곳에서 볼 수 있습니다.',null],['개발 도구','GitHub','프로젝트와 소스 코드를 확인할 수 있는 공식 사이트입니다. 예시 항목입니다.','https://github.com/']], '수업·평가':[['문항 제작','ExamPool','직접 만든 출제 도구의 상세 안내입니다.','https://www.psy.ai.kr/projects/exam-pool.html'],['과학 그림','5E','과학 그림 제작 도구의 상세 안내입니다.','https://www.psy.ai.kr/projects/physics-draw.html']], '문서·행정':[['한글 편집','HwpPalette','한글 편집 도구의 상세 안내입니다.','https://www.psy.ai.kr/projects/hwp-palette.html']], '생산성':[['반복 작업','EveryKey','반복되는 컴퓨터 작업을 줄이는 도구입니다.','https://www.psy.ai.kr/projects/everykey.html']]};
function finder(cat='AI·개발',idx=0){const items=categories[cat],item=items[idx];openWindow('추천 도구함',`<div class="finder"><section><p class="muted">분야</p>${Object.keys(categories).map(k=>`<button class="row ${k===cat?'active':''}" data-cat="${k}">▱ ${k}</button>`).join('')}</section><section><p class="muted">${cat}</p>${items.map((v,i)=>`<button class="row ${i===idx?'active':''}" data-item="${i}" data-category="${cat}">▱ ${v[0]}<small>${v[1]}</small></button>`).join('')}</section><section class="detail"><p class="muted">${cat} / ${item[0]}</p><h1>${item[1]}</h1><p>${item[2]}</p>${item[3]?`<a class="primary" target="_blank" rel="noopener" href="${item[3]}">공식 안내 열기 ↗</a>`:'<p class="muted">추천 항목은 구현 시 관리자 화면에서 등록합니다.</p>'}<p class="form-note">폴더 탐색 시연용 구성입니다.</p></section></div>`)}
function programs(){openWindow('만든 도구',`<div class="content"><h1>교실에서 시작한 도구들</h1><p class="muted">프로그램을 선택하면 현재 사이트의 상세 안내로 연결됩니다.</p><div class="cards">${apps.map(([name,icon,url,desc])=>`<article class="card"><img src="assets/${icon}.svg" alt=""><h2>${name}</h2><p>${desc}</p><a href="https://www.psy.ai.kr/projects/${url}.html" target="_blank" rel="noopener">상세 안내 ↗</a></article>`).join('')}</div><h2>도구를 함께 쓰는 방법</h2><p>문항 구성 · ExamPool → 그림 제작 · 5E → 한글 편집 · HwpPalette</p></div>`)}
function training(){openWindow('연수 자료',`<div class="finder"><section><button class="row active">▱ 전체 연수</button></section><section><button class="row active">시험문제 제작 도구 활용<small>자료실 구성 예시</small></button></section><section class="detail"><p class="muted">예시 폴더</p><h1>연수 자료실</h1><p>연수 안내, 발표 자료, 실습 파일을 한곳에서 찾도록 구성합니다.</p><p>아직 실제 연수 파일은 등록되지 않았습니다.</p><button class="primary" data-open="programs">관련 프로그램 보기</button></section></div>`)}
function about(){openWindow('소개',`<div class="content"><p class="muted">PHYSICS TEACHER · SEOUL</p><h1>박승연</h1><h2>교사가 한가하면, 교육이 성장한다.</h2><p>수업과 행정의 번거로움을 줄이는 도구를 만듭니다.</p><a class="primary" target="_blank" rel="noopener" href="https://www.psy.ai.kr/">현재 홈페이지 · 채널과 협업 안내 ↗</a></div>`)}
const actions={programs,recommend:()=>finder(),training,about,records:()=>journal('2026-08-30'),add:()=>linkForm(),play:()=>{openWindow('물리 놀이터','<div class="content"><h1>진자의 주기</h1><p>줄의 길이에 따른 단진자의 주기를 확인해보세요.</p><label>길이 <input id="length" type="range" min="10" max="200" value="100"></label><h2 id="period">1.00 m · 주기 약 2.01초</h2><p class="muted">작은 진폭, 중력가속도 9.81 m/s²를 가정합니다.</p></div>');$('#length').oninput=e=>{$('#period').textContent=`${(e.target.value/100).toFixed(2)} m · 주기 약 ${(2*Math.PI*Math.sqrt(e.target.value/100/9.81)).toFixed(2)}초`}}};
function icon(label,kind,action){return `<button class="desktop-icon" data-open="${action}"><span class="icon ${kind}">${kind==='folder'?'':kind==='sheet'?'▦':kind==='link'?'↗':'≡'}</span><span>${label}</span></button>`}
function render(){ $('#noteText').textContent=note;$('#icons').innerHTML=icon('연수 자료','folder','training')+icon('만든 도구','folder','programs')+icon('추천 도구함','folder','recommend')+icon('소개','noteicon','about')+shortcuts.map((s,i)=>`<button class="desktop-icon" data-shortcut="${i}">${s.image?`<img src="${esc(s.image)}" alt="">`:`<span class="icon ${s.kind}">${s.kind==='sheet'?'▦':'↗'}</span>`}<span>${esc(s.title)}</span></button>`).join('')+(editing?icon('바로가기 추가','link','add'):'');$('#editNote').hidden=!editing;$('#edit').textContent=editing?'편집 체험 종료':'편집 체험';$('#dock').innerHTML=apps.slice(0,3).map(([name,im,url])=>`<button data-app="${url}"><img src="assets/${im}.svg" alt=""><span>${name}</span></button>`).join('')+[['연수 자료','training','▱'],['추천 도구함','recommend','▱'],['기록','records','▦'],['놀이터','play','⌁']].map(([n,a,c])=>`<button data-open="${a}"><span class="icon noteicon">${c}</span><span>${n}</span></button>`).join('')}
function linkForm(){openWindow('바로가기 추가',`<form id="linkForm"><p class="form-note">편집 체험 · 이 브라우저에만 저장되며 공개 사이트에 반영되지 않습니다.</p><label>이름<input name="title" required maxlength="30" placeholder="예: 연수 설문"></label><label>연결 주소<input name="url" type="url" required placeholder="https://..."></label><label>기본 아이콘<select name="kind"><option value="link">링크</option><option value="sheet">스프레드시트</option></select></label><label>내 아이콘 이미지 (선택)<input name="image" type="file" accept="image/png,image/jpeg,image/webp"></label><p id="formError" role="alert"></p><button class="primary">바탕화면에 추가</button></form>`);$('#linkForm').onsubmit=async e=>{e.preventDefault();const f=e.target,url=new URL(f.url.value);if(!['https:','http:'].includes(url.protocol)){$('#formError').textContent='http 또는 https 주소를 입력해주세요.';return}const file=f.image.files[0];if(file&&file.size>200000){$('#formError').textContent='아이콘은 200KB 이하로 선택해주세요.';return}let image='';if(file){image=await new Promise(resolve=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.readAsDataURL(file)})}const next=[...shortcuts,{title:f.title.value.trim(),url:url.href,kind:f.kind.value,image}];if(store('studio-links',next)){shortcuts=next;render();closeWindow()}else $('#formError').textContent='저장하지 못했습니다. 아이콘 크기를 줄여주세요.'}}
$('#editNote').onclick=()=>{openWindow('메모 수정','<form id="noteForm"><label>방문자에게 남기는 메모<textarea name="note" maxlength="500"></textarea></label><p class="form-note">이 브라우저에만 저장됩니다.</p><button class="primary">저장</button></form>');$('#noteForm textarea').value=note;$('#noteForm').onsubmit=e=>{e.preventDefault();const value=e.target.note.value;if(store('studio-note',value)){note=value;render();closeWindow()}}};
$('#enter').onclick=()=>{$('#entrance').hidden=true;$('#desktop').hidden=false;$('#desktop').classList.add('entering');$('#return').focus()};$('#return').onclick=()=>{$('#desktop').hidden=true;$('#entrance').hidden=false;$('#enter').focus()};$('#edit').onclick=()=>{editing=!editing;render();$('#saveState').textContent=editing?'편집 체험: 변경은 이 브라우저에만 저장됩니다.':''};$('#prev').onclick=()=>{month.setMonth(month.getMonth()-1);calendar()};$('#next').onclick=()=>{month.setMonth(month.getMonth()+1);calendar()};$('#allRecords').onclick=()=>journal('2026-08-30');
document.addEventListener('click',e=>{const b=e.target.closest('[data-open],[data-cat],[data-item],[data-date],[data-app],[data-shortcut]');if(!b)return;if(b.dataset.open)actions[b.dataset.open]?.();if(b.dataset.cat)finder(b.dataset.cat);if(b.dataset.item)finder(b.dataset.category,Number(b.dataset.item));if(b.dataset.date)journal(b.dataset.date);if(b.dataset.app)window.open(`https://www.psy.ai.kr/projects/${b.dataset.app}.html`,'_blank','noopener');if(b.dataset.shortcut){const s=shortcuts[Number(b.dataset.shortcut)];if(editing){openWindow('바로가기 관리',`<div class="content"><h1>${esc(s.title)}</h1><p>${esc(s.url)}</p><a class="primary" target="_blank" rel="noopener" href="${esc(s.url)}">열기 ↗</a> <button id="removeShortcut">바로가기 삭제</button></div>`);$('#removeShortcut').onclick=()=>{shortcuts.splice(Number(b.dataset.shortcut),1);store('studio-links',shortcuts);render();closeWindow()}}else window.open(s.url,'_blank','noopener')}});
let drag=null;$('.titlebar').addEventListener('pointerdown',e=>{if(e.target.closest('button')||innerWidth<700)return;drag={x:e.clientX,y:e.clientY};e.currentTarget.setPointerCapture(e.pointerId)});$('.titlebar').addEventListener('pointermove',e=>{if(drag)$('#window').style.transform=`translate(${Math.max(-150,Math.min(150,e.clientX-drag.x))}px,${Math.max(-80,Math.min(80,e.clientY-drag.y))}px)`});$('.titlebar').addEventListener('pointerup',()=>drag=null);calendar();render();
$('#desktop').addEventListener('animationend',()=>$('#desktop').classList.remove('entering'));
